config/routes.rb
Hiphip::Application.routes.draw do
  resources :countries











  match ':controller(/:action(/:id))(.:format)' , via: [:post, :get]
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :age, :email, :name
  belongs_to :group
  
  scope :smiths, where("name LIKE ?", "%Smith%")
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render action: 'show', status: :created, location: @country }
      else
        format.html { render action: 'new' }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :direction, :picture, :distance, :coordinates)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

def test
user = User.create
render :text => user.attributes
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def get
@users = [
{:name => "John Smith", :email => "john.smith@gmail.com"},
{:name => "Mary Doe", :email => "mary.doe@gmail.com"}
]
end

def show
@name = params[:name]
end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.erb
<%= form_for(@country) do |f| %>
  <% if @country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% @country.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :direction %><br>
    <%= f.text_field :direction %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :distance %><br>
    <%= f.number_field :distance %>
  </div>
  <div class="field">
    <%= f.label :coordinates %><br>
    <%= f.number_field :coordinates %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing country</h1>

<%= render 'form' %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<h1>Listing countries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Direction</th>
      <th>Picture</th>
      <th>Distance</th>
      <th>Coordinates</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td><%= country.direction %></td>
        <td><%= country.picture %></td>
        <td><%= country.distance %></td>
        <td><%= country.coordinates %></td>
        <td><%= link_to 'Show', country %></td>
        <td><%= link_to 'Edit', edit_country_path(country) %></td>
        <td><%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Country', new_country_path %>

app/views/countries/new.html.erb
<h1>New country</h1>

<%= render 'form' %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @country.name %>
</p>

<p>
  <strong>Direction:</strong>
  <%= @country.direction %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @country.picture %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @country.distance %>
</p>

<p>
  <strong>Coordinates:</strong>
  <%= @country.coordinates %>
</p>

<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
 
 <title>Hiphip</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>

  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>

</head>

<body>


<%= yield %>


</body>

</html>

app/views/users/get.html.erb
<table border="1">
<% @users.each do |user| %>
<tr>
<td><%= link_to(user[:name], {:action => 'show', :name => user[:name]}) %></td>
<td><%= link_to(user[:email], "mailto:#{user[:email]}") %></td>
</tr>
<% end %>
</table>

<br><br>

<%= Time.now %>

app/views/users/show.html.erb
<%= @name %>